default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_IP_ADDRESS'] %>
  port: 5432
  pool: 10

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DB'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB'] %>